### ISSUE TITLE
404 Handler for EPiServer Causing Redirect Loop

### ISSUE THREAD

**Issue by JakubHromada** [Geta/404handler#46]
A bug causing a redirect loop occurs when an existing redirect does match a part of a URL string after the domain name.
 
I took the following steps to replicate:
 
1. Fresh installation of latest Episerver Alloy, Episerver CMS 10.10.4, Episerver CMS.UI 10.10.12
2. Install 404 Handler for EPiServer 10.1.1 using Package manager console
3. Create a redirect from ‘/en/about-us/’ to ‘/en/about-us/news-events’
4. Navigate to any of the following: 
a. localhost:xxxxx/en/about-us/news-events-wrong-word
b. localhost:xxxxx/en/about-us/news-events/wrong-page
5. Instead of seeing a 404 response, the 404 handler creates a redirect loop resulting in 400 Bad Request response
 
Thanks
Jakub

**Comment by kennygutierrez** [comment]
Looks like they're making progress: 
![image](https://user-images.githubusercontent.com/5246906/36048489-08feaa16-0da5-11e8-98ad-34d248faa2d2.png)

**Comment by kennygutierrez** [comment]
Hey, I'm so happy to see this is getting resolved! Pardon my ignorance but how long after a fix is finished does it take to show up as an updated package in nuget?

**Comment by marisks** [comment]
I hope to publish the new version next week

**Comment by marisks** [comment]
The package with the fix is available now.

**Comment by kennygutierrez** [comment]
Thank you Marisks, we will try it out!

**Comment by kaylabranch** [comment]
Hi @marisks - can you please tell me if the fix for this issue is in package v10.3.0 or in v11.*? Both?
Thank you!

**Comment by marisks** [comment]
In both

**Comment by kaylabranch** [comment]
Hello - I have updated to the latest package, and I'm still seeing errors with URLs like the following:

![image](https://user-images.githubusercontent.com/25715079/37485327-1abaec6e-2859-11e8-87d6-ae3f007f81ed.png)

They result in URLs like this:

/resources/bloglogloglogloglogloglogloglogloglogloglogloglogloglogloglog/thisisablog

and:

/product/health-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-insurance-article/what-hipaa-and-how-will-it-affect-your-small-business?q=article/what-hipaa-and-how-will-it-affect-your-small-business

Any insight into this issue?
Thanks,
Kayla
